Update Motor Follower Example 2025
Fue-Di/SPARK-MAX-Examples pull request #1
Opened 2024-11-06 22:32 UTC by Fue-Di

Update the motor follower example code to use REVLib 2025.

2024-11-13 14:44 UTC, doleksy approved these changes

2024-11-14 23:30 UTC, jfabellera approved these changes

2024-11-14 23:32 UTC, jfabellera requested changes

2024-11-14 23:32 UTC, jfabellera commented on Java/Motor Follower/src/main/java/frc/robot/Robot.java
> +    leadMotor.configure(emptyConfig, ResetMode.kResetSafeParameters, PersistMode.kNoPersistParameters);
We should be recommending users to use `kPersistParameters`

2024-11-14 23:51 UTC, merged